### ISSUE TITLE
problem with analysis output with aov.phylo (geiger)

### ISSUE THREAD

**Issue by mstrelin** [mwpennell/geiger-v2#11]
I'm using the aov.phylo function (R package geiger) to do phylogenetic manova. I used the same phylogeny to run the manova using two different data sets. I'm wondering about why Pr(phy) is the same in both analyses... here is the output of these two analyses

Thanks!

Marina

Structure 1

Multivariate Analysis of Variance Table

Response: dat
          Df   Wilks approx-F num-Df den-Df    Pr(>F) Pr(phy)  
group      1 0.29354   13.237      2     11 0.0011807 0.01961 *
Residuals 12                                                   
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Structure 2

Multivariate Analysis of Variance Table

Response: dat
          Df   Wilks approx-F num-Df den-Df    Pr(>F) Pr(phy)  
group      1 0.27139    8.949      3     10 0.0035049 0.01961 *
Residuals 12                                                   
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

**Comment by lukejharmon** [comment]
I expect that the answer to this question has to do with the nsim parameter to the function. The smallest p-value one can possibly get is 1/(nsim+1). Since you have 0.01961, which is 1/51, I wonder if you are setting nsim=50 as in the example in the help file? Try setting nsim=1000 and see if you get different (and more precise) results.

**Comment by mstrelin** [comment]
Hi Luke! Thanks a lo for your answert! Yes, I also realized later that this
was the problem...

Best,

Marina


2015-03-31 17:06 GMT-03:00 Luke Harmon <notifications@github.com>:
